import { createHash } from "node:crypto";
import { createReadStream } from "node:fs";
import {
  copyFile,
  mkdir,
  readFile,
  realpath,
  rm,
  stat,
} from "node:fs/promises";
import path from "node:path";
import { imageSize } from "image-size";

const imageExtensions = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".webp",
  ".svg",
  ".gif",
  ".avif",
]);
const videoTypes = {
  ".mp4": "video/mp4",
  ".mov": "video/quicktime",
  ".m4v": "video/mp4",
  ".webm": "video/webm",
  ".ogv": "video/ogg",
};

export async function resolveAssets(content, root, { write = true } = {}) {
  const files = new Map();
  let bytes = 0;
  let assetsRoot;
  async function walk(value, field) {
    if (Array.isArray(value)) {
      const result = [];
      for (const [index, entry] of value.entries())
        result.push(await walk(entry, `${field}[${index}]`));
      return result;
    }
    if (!value || typeof value !== "object" || value.enabled === false)
      return value;
    if (!Object.hasOwn(value, "path")) {
      const result = {};
      // Sequential traversal deduplicates shared assets before copying them.
      for (const [key, entry] of Object.entries(value))
        result[key] = await walk(entry, `${field}.${key}`);
      return result;
    }
    if (!value.path.startsWith("assets/") || value.path.includes("\\"))
      throw new Error(`${field}.path: use a repository-relative assets/ path`);
    assetsRoot ??= await realpath(path.join(root, "assets"));
    let source;
    try {
      source = await realpath(path.resolve(root, value.path));
    } catch {
      throw new Error(`${field}.path: file not found: ${value.path}`);
    }
    if (!source.startsWith(assetsRoot + path.sep))
      throw new Error(`${field}.path: must stay inside assets/`);
    const info = await stat(source);
    if (!info.isFile() || !info.size)
      throw new Error(`${field}.path: expected a non-empty file`);
    const ext = path.extname(source).toLowerCase();
    const isImage = imageExtensions.has(ext);
    const expectsVideo = field.endsWith(".video");
    if (expectsVideo ? !videoTypes[ext] : !isImage)
      throw new Error(
        `${field}.path: unsupported ${expectsVideo ? "video" : "image"} extension ${ext}`,
      );
    if (!files.has(source)) {
      const hash = createHash("sha256");
      let first = true;
      for await (const chunk of createReadStream(source)) {
        if (
          first &&
          chunk
            .subarray(0, 200)
            .toString()
            .startsWith("version https://git-lfs.github.com/spec/v1")
        ) {
          throw new Error(
            `${field}.path: ${value.path} is a Git LFS pointer. Run git lfs pull.`,
          );
        }
        first = false;
        hash.update(chunk);
      }
      const stem = path
        .basename(source, path.extname(source))
        .replace(/[^a-zA-Z0-9_-]+/g, "-");
      const asset = {
        url: `assets/media/${stem}-${hash.digest("hex").slice(0, 12)}${ext}`,
        size: info.size,
      };
      if (isImage) {
        try {
          const dimensions = imageSize(await readFile(source));
          if (!dimensions.width || !dimensions.height)
            throw new Error("missing dimensions");
          asset.width = dimensions.width;
          asset.height = dimensions.height;
        } catch {
          throw new Error(
            `${field}.path: cannot read image dimensions; check the image file`,
          );
        }
      }
      files.set(source, asset);
      bytes += info.size;
    }
    const resolved = { ...value, ...files.get(source) };
    if (expectsVideo) {
      resolved.types = value.types?.length ? value.types : [videoTypes[ext]];
      resolved.aspectRatio = value.aspectRatio ?? "16 / 9";
      if (
        !/^\d+(?:\.\d+)?\s*\/\s*\d+(?:\.\d+)?$/.test(resolved.aspectRatio) ||
        resolved.aspectRatio.split("/").some((n) => Number(n) <= 0)
      ) {
        throw new Error(
          `${field}.aspectRatio: use positive dimensions such as "16 / 9"`,
        );
      }
      if (value.poster)
        resolved.poster = await walk(value.poster, `${field}.poster`);
    }
    return resolved;
  }
  const resolved = await walk(content, "content");
  if (bytes > 950_000_000)
    throw new Error(
      "Media exceeds 950 MB; leave room within the 1 GB Pages limit.",
    );
  if (write) {
    const output = path.join(root, "website/public/assets");
    await mkdir(path.join(output, "media"), { recursive: true });
    for (const [source, asset] of files)
      await copyFile(source, path.join(root, "website/public", asset.url));
    // Remove only files generated by this pipeline, after all inputs are valid.
    const { readdir } = await import("node:fs/promises");
    const keep = new Set(
      [...files.values()].map((asset) => path.basename(asset.url)),
    );
    for (const file of await readdir(path.join(output, "media"))) {
      if (!keep.has(file)) await rm(path.join(output, "media", file));
    }
  }
  return { content: resolved, count: files.size, bytes };
}
